version: "3.9"

services:
  nginx:
    image: lab11-nginx:${{ matrix.architecture }}
    ports:
      - 8888:8888
    networks:
      - backend

  php:
    image: lab11-php:${{ matrix.architecture }}
    depends_on:
      - mysql
    networks:
      - backend
    ports:
      - 8080:80

  mysql:
    environment:
      - MYSQL_ROOT_PASSWORD=lab11
    image: lab11-mysql:${{ matrix.architecture }}
    ports:
      - 3307:3306
    networks:
      - backend

  phpmyadmin:
    image: lab11-phpmyadmin:${{ matrix.architecture }}
    ports:
      - 6001:80
    networks:
      - backend

networks:
  backend:
