name: Build and Push Images 

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [amd64, arm64]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Build and Push Nginx Image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t wfgen/nginx:${{ matrix.architecture }} -f Dockerfile.nginx .
          docker push wfgen/nginx:${{ matrix.architecture }}

      - name: Build and Push PHP Image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t wfgen/php:${{ matrix.architecture }} -f Dockerfile.php .
          docker push wfgen/php:${{ matrix.architecture }}

      - name: Build and Push MySQL Image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t wfgen/mysql:${{ matrix.architecture }} -f Dockerfile.mysql .
          docker push wfgen/mysql:${{ matrix.architecture }}

      - name: Build and Push phpMyAdmin Image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t wfgen/phpmyadmin:${{ matrix.architecture }} -f Dockerfile.phpmyadmin .
          docker push wfgen/phpmyadmin:${{ matrix.architecture }}
