name: Build and Push Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [amd64, arm64]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username wfgen --password-stdin

      - name: Build and Push Nginx Image
        run: |
          docker buildx build -t wfgen/nginx:${{ matrix.architecture }} -f Dockerfile.nginx --platform linux/${{ matrix.architecture }} .
          docker push wfgen/nginx:${{ matrix.architecture }}

      - name: Build and Push PHP Image
        run: |
          docker buildx build -t wfgen/php:${{ matrix.architecture }} -f Dockerfile.php --platform linux/${{ matrix.architecture }} .
          docker push wfgen/php:${{ matrix.architecture }}

      - name: Build and Push MySQL Image
        run: |
          docker buildx build -t wfgen/mysql:${{ matrix.architecture }} -f Dockerfile.mysql --platform linux/${{ matrix.architecture }} .
          docker push wfgen/mysql:${{ matrix.architecture }}

      - name: Build and Push phpMyAdmin Image
        run: |
          docker buildx build -t wfgen/phpmyadmin:${{ matrix.architecture }} -f Dockerfile.phpmyadmin --platform linux/${{ matrix.architecture }} .
          docker push wfgen/phpmyadmin:${{ matrix.architecture }}
